<a href="https://colab.research.google.com/github/Gustafary02/Entrega-An-lisis-Barcelona-21-22/blob/main/Arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generar un arreglo 5x3 con números aleatorios entre 0 y 100
arreglo = np.random.randint(0, 101, size=(5, 3))

print(arreglo)


[[ 5 59 71]
 [96 97 48]
 [49 38 20]
 [78 39 20]
 [64  6 29]]


In [ ]:
# Calcular la suma total
suma_total = np.sum(arreglo)

print("Arreglo:")
print(arreglo)
print("\nSuma total de los valores:", suma_total)

Arreglo:
[[ 5 59 71]
 [96 97 48]
 [49 38 20]
 [78 39 20]
 [64  6 29]]

Suma total de los valores: 719


In [ ]:
promedios_columnas = np.mean(arreglo, axis=0)
print("\nPromedio de cada columna:", promedios_columnas)


Promedio de cada columna: [58.4 47.8 37.6]


In [ ]:
# Generar una matriz 10x10 con enteros aleatorios entre 0 y 9
matriz = np.random.randint(0, 10, size=(10, 10))

print("Matriz 10x10:")
print(matriz)

Matriz 10x10:
[[5 6 8 8 7 1 7 7 2 9]
 [6 1 6 4 3 8 7 1 3 9]
 [7 2 3 5 6 4 5 4 8 6]
 [3 4 5 0 7 6 0 5 3 9]
 [4 3 7 8 6 8 6 5 6 4]
 [2 0 0 3 3 4 2 8 0 0]
 [1 3 6 7 7 1 3 7 4 5]
 [4 2 1 8 0 1 7 2 0 5]
 [0 2 0 0 8 6 3 6 2 8]
 [1 4 4 3 8 1 8 1 9 6]]


In [ ]:
# Reemplazar valores mayores que 5 con -1
matriz[matriz > 5] = -1

print("Matriz modificada:")
print(matriz)

Matriz modificada:
[[ 5 -1 -1 -1 -1  1 -1 -1  2 -1]
 [-1  1 -1  4  3 -1 -1  1  3 -1]
 [-1  2  3  5 -1  4  5  4 -1 -1]
 [ 3  4  5  0 -1 -1  0  5  3 -1]
 [ 4  3 -1 -1 -1 -1 -1  5 -1  4]
 [ 2  0  0  3  3  4  2 -1  0  0]
 [ 1  3 -1 -1 -1  1  3 -1  4  5]
 [ 4  2  1 -1  0  1 -1  2  0  5]
 [ 0  2  0  0 -1 -1  3 -1  2 -1]
 [ 1  4  4  3 -1  1 -1  1 -1 -1]]


In [ ]:
!pip install opencv-python

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import cv2
import numpy as np


In [ ]:
# Ruta a la imagen en Google Drive

ruta_imagen = "/content/drive/MyDrive/FOTO PARA COLAB GOOGLE/fc-barcelona.jpg"


# Leer la imagen
imagen = cv2.imread(ruta_imagen)

# Ver estadísticas básicas
print("Dimensiones de la imagen:", imagen.shape)

# Estadísticas por canal (BGR)
min_valores = imagen.min(axis=(0, 1))
max_valores = imagen.max(axis=(0, 1))
promedio_canales = imagen.mean(axis=(0, 1))

print(f"Mínimos por canal (BGR): {min_valores}")
print(f"Máximos por canal (BGR): {max_valores}")
print(f"Promedio por canal (BGR): {promedio_canales}")


Dimensiones de la imagen: (2160, 5120, 3)
Mínimos por canal (BGR): [0 0 0]
Máximos por canal (BGR): [255 255 255]
Promedio por canal (BGR): [48.23930302 13.45547463 17.49109918]
